global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'clickhouse'
    static_configs:
      - targets:
        - 'clickhouse1:9363'
        - 'clickhouse2:9363'
        - 'clickhouse3:9363'
        - 'clickhouse4:9363'
        labels:
          cluster: 'production'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
